config/routes.rb
QuizProject::Application.routes.draw do
  get "statistics/index"
  resources :users
  resources :questions
  root 'questions#generate_question'

  post 'questions/:id/result' => 'questions#show_result', as: :show_result

  get '/login' => 'users#sign_in', as: :sign_in
  post '/login' => 'sessions#create', as: :new_session
  delete '/sign_out' => 'sessions#destroy', as: :sign_out
  get "statistics/index" => 'statistics#index', as: :stats

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  def correct?
    user_answer == question.answer
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers, dependent: :destroy

  def self.generate_for(user)
    random_questions = self.order("RANDOM()")
    filter(random_questions, user)
  end

  def author
    self.user.username
  end

  def self.filter(random_questions, user)
    possible_questions = random_questions.select { |question| question.user != user && question.hasnt_been_answered(user) }
    possible_questions.empty? ? nil : possible_questions.first
  end

  def hasnt_been_answered(user)
    answers.all? { |answer| answer.user != user }
  end

  def difficulty
    return nil if answers.empty?
    groups = answers.partition { |ans| ans.correct? }
    decimal = groups[0].count.to_f / answers.count
    percentage = decimal * 100
    percentage.to_i
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, 
            :uniqueness => true, 
            :presence => true

  validates :username, 
            :uniqueness => true, 
            :presence => true

  validates_presence_of :password, :on => :create

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  def ask_question(options)
    Question.create(options.merge(user: self))
  end

  def score
    return nil if answers.empty?
    groups = answers.partition { |answer| answer.correct? }
    decimal = groups[0].count.to_f / answers.count
    percentage = decimal * 100
    percentage.to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :error
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate, only: [:generate_question]

  def show
    @question = Question.find(params[:id])
  end

  def show_result
    user = User.find(session[:user_id])
    @question = Question.find(params[:id])
    @user_answer = true if params[:True]
    @user_answer = false if params[:False]   
    Answer.create(user_answer: @user_answer, user: user, question: @question)
  end
   
  def generate_question
    @question = Question.generate_for(User.find(session[:user_id]))
    if @question
      render :show
    else
      render :index
    end
  end

  def new
    @question = Question.new
  end

  def create
    if session[:user_id]
      User.find(session[:user_id]).ask_question(question_params)
    else
      Question.create(question_params)
    end
    redirect_to root_url, notice: "Question added!"
  end

  private

  def question_params
    params.require(:question).permit(:text, :answer)
  end

  def answer_params
    params.require(:True,:False)
  end

  def authenticate
    unless session[:user_id]
      # redirect_to sign_in_path
      render 'users/sign_in'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
      user = User.find_by_username(params[:username])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path, :notice => "Welcome #{user.username}!"
      else
        flash.alert = "Invalid username or password"
        redirect_to sign_in_path
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to root_path :notice => "logged out"
    end

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    questions = Question.all.select { |q| !q.difficulty.nil? }.sort_by(&:difficulty)
    @hardest_question = questions.first
    @easiest_question = questions.last

    @users = User.all.select { |q| !q.score.nil? }.sort_by(&:score).reverse
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome #{user.username}!"
    else
      redirect_to new_user_path, error: user.errors.keys[0].to_s.capitalize.gsub('_', ' ') + ' ' + user.errors.values[0][0]
    end
  end

  def sign_in
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    begin
      User.find(session[:user_id])
    rescue
      nil
    end
  end

end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= yield (:body_class) %>">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "#{name} flash" %>
  <% end %>

  <%= yield %>
  
  <footer>
    <ul class="user-links left">
      <%if current_user %>    
        <li><%= link_to "#{current_user.username}'s Profile", user_path(current_user.id) %></li>
        <li><%= link_to "Stats", stats_path %></li>
      <% else %>
        <li><%= link_to "Sign In", sign_in_path %></li>
      <% end %>
    </ul>
    <a href="/" id="logo">QuizApp</a>
    <ul class="user-links right">
      <%if current_user%>
        <li><%= link_to "Sign Out", sign_out_path, method: 'delete' %></li>
        <li><%= link_to "Add Question", new_question_path %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_path %></li>
      <% end %>
    </ul>
  </footer>
</body>
</html>

app/views/questions/index.html.erb
<% content_for :body_class, "body-no-question" %>
<p class="apology">No more questions, sorry.</p>

app/views/questions/new.html.erb
<% content_for :body_class, "body-new-question" %>
<%= form_for @question, url: {action: "create"}, html: {class: 'new-question-form'} do |f| %>
  <%= f.text_area :text, rows: 4, placeholder: 'What do you want to ask?' %>
  <%= f.radio_button(:answer, "true", checked: 'checked') %>
  <%= f.label(:answer_true, "True", class: 'button button-true') %>
  <%= f.radio_button(:answer, "false") %>
  <%= f.label(:answer_false, "False", class: 'button button-false') %>
  <%= f.submit "Create", class: 'button button-create' %> 
<% end %>

app/views/questions/show.html.erb
<% content_for :body_class, "body-question" %>
<p class="question-text"><%= @question.text %></p>
<%= form_tag(show_result_path(@question)) do %>
<!-- <form method="post" action="/questions/<%= @question.id %>/result"> -->
  <input type="submit" class="button button-true" name="True" value="True" />
  <input type="submit" class="button button-false" name="False" value="False" />
<% end %>

app/views/questions/show_result.html.erb
<% if @user_answer == @question.answer %>
  <% content_for :body_class, "body-result body-correct" %>
  <p class="result_text">Correct!</p>
<% else %>
  <% content_for :body_class, "body-result body-incorrect" %>
  <p class="result_text">Incorrect</p>
<% end %>
<a href="/" class="button button-next">Next</a>

app/views/statistics/index.html.erb
<% content_for :body_class, "body-stats" %>
<p>There are <span class="questions-count"><%= Question.all.count %></span> questions</p>
<hr />
<% if @hardest_question %>
  <p>The hardest question is:</p>
  <p class="difficult-question"><span><%= @hardest_question.text %></span></p>
  <p>Which was only answered successfully <span class="question-difficulty"><%= @hardest_question.difficulty %>%</span> of the time</p>
  <hr />
<% end %>
<% if @easiest_question %>
  <p>The easiest question is:</p>
  <p class="difficult-question"><span><%= @easiest_question.text %></p></span>
  <p>Which was answered successfully <span class="question-difficulty"><%= @easiest_question.difficulty %>%</span> of the time</p>
  <hr />
<% end %>
<p>Top Scores</p>
<table>
  <% @users.each_with_index do |user, index| %>
  <tr>
    <td><%= index + 1 %></td>
    <td><%= user.username %></td>
    <td><%= user.score %>%</td>
  </tr>
  <% end %>
</table>
<hr />
<p>That's all we've got for now</p>

app/views/users/new.html.erb
<% content_for :body_class, "body-sign-up" %>
<%= form_for @user, url: {action: "create"} do |f| %>
  <%= f.text_field     :username, placeholder: 'Username' %>
  <%= f.text_field     :email, placeholder: 'Email' %>
  <%= f.password_field :password , placeholder: 'Password' %>
  <%= f.password_field :password_confirmation, placeholder: 'Confirm Password' %>
  <%= f.submit "Sign Up", class: 'button' %>
<% end %>

app/views/users/show.html.erb
<% content_for :body_class, "body-profile" %>
<h1><%= @user.username.capitalize %></h1>
<span class="score-title">Score:</span>
<span class="score"><%= @user.score %>%</span>

app/views/users/sign_in.html.erb
<% content_for :body_class, "body-sign-in" %>
<%= form_tag(new_session_path, method: "post") do %>
  <%= text_field_tag :username, nil, placeholder: 'Username' %>
  <%= password_field_tag :password, nil, placeholder: 'Password' %>
  <%= button_tag "Sign In", class: 'button' %>
<% end %>

app/views/welcome/index.html.erb
<h1>"Is the sky blue"</h1>